{% set name = "compositionspace" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/compositionspace-{{ version }}.tar.gz
  sha256: 98095d3134b8ec9b66338197dc15e21eb21fc353fc9a5c086fc138e9161ccb9f

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - python >=3.8
    - pytest-runner
    - pip
  run:
    - python >=3.8
    - numpy
    - matplotlib-base
    - pandas
    - h5py
    - scikit-learn
    - tqdm
    - ifes-apt-tc-data-modeling
    - trimesh
    - pyyaml
    - flatdict
    - lxml
    - jupyterlab-h5web

test:
  imports:
    - compositionspace
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/compositionspace/
  summary: APT analysis tools
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - srmnitc
