{% set name = "compositionspace" %}
{% set version = "0.0.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/compositionspace-{{ version }}.tar.gz
  sha256: f610d617f21c4cd2f0d41afc38b03bdfbe44b8401cc31d1a3153060511262500

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - python >=3.8
    - pytest-runner
    - pip
  run:
    - python >=3.8
    - numpy
    - matplotlib-base
    - pandas
    - h5py
    - scikit-learn
    - tqdm
    - pyevtk
    - pyyaml
    - pyvista
    - ipywidgets
    - ipyvtklink
    - panel

test:
  imports:
    - compositionspace
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/compositionspace/
  summary: APT analysis tools
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - srmnitc
